### PR TITLE
bump rets version to 0.8.0 for new release

### PR DESCRIPTION
**Pull request by dougcole**

### CODE REVIEW

**Comment by summera** [comment]
@dougcole not sure what happened here but when you merged this in we went back to making httpclient version less specific. https://github.com/estately/rets/commit/61b521f3b183863ab0d15c51b3854baa25c85e9c#diff-22986d4f6456ebe082f62c8863f7974bL28

This essentially undid https://github.com/estately/rets/pull/109/files that you just merged in

**Comment by dougcole** [comment]
welp, that's embarrassing, thanks for the catch!

**Comment by dougcole** [comment]
@summera The problem is/was that with `hoe` the gemspec is auto-generated based on the values set in the `Rakefile`, so the value needs to be bumped there and the gemspec regenerated.

**Comment by summera** [comment]
Oh! That would make sense haha. My bad on that. Never used the `hoe` gem before

**Pull request merged**
