### PR TITLE
dont retry 20201 responses

### PR DESCRIPTION
**Pull request by hfaulds**
An example of how we could avoid retries when the server returns 20201 (similar to https://github.com/estately/rets/issues/79)

### CODE REVIEW

**Comment by VasylYaremkiv** [comment]
Hey guys. What is the status of this issue? Our team would like to have this fixed ASAP.

**Comment by hfaulds** [comment]
Added some tests (and fixed the conditional being the wrong way around), this is good to go in my book.

**Comment by dougcole** [comment]
I think this looks great. I think we should make `: no_records_not_an_error` default to true with the next major version as that makes more sense in the long run, imo.

I also think this deserves documentation, but I'll open a new issue for that.

**Comment by dougcole** [comment]
OK, this is merged into master and I'm prepping a new release here https://github.com/estately/rets/pull/93 - please try it out if you can. I'm going to leave it open for a few days while we test the update and make sure it works well for us, then I'll merge and push a new gem.

**Pull request merged**
